version: "3.8"
services:
  app:
    image: myapp:latest
    build:
      context: .
      target: dev
      labels:
        - "com.example.description=My App Development Environment"
      tags:
        - "development"
    ports:
      - "3900:3900"
    environment:
      - NODE_ENV=dev
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - REDIS_URL=redis://redis:6379
    # volumes:
    #   - .:/app
    networks:
      - mynetwork
    depends_on:
      - mongo
      - redis
    restart: always
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork
  redis:
    image: redis:latest
    # ports:
    #   - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  mongo-data:
    driver: local
    # provide name for the volume
    name: mongo-data

  redis-data:
    driver: local
    # provide name for the volume
    name: redis-data
